//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TollApp_Backend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TOLL_LocalDBEntities : DbContext
    {
        public TOLL_LocalDBEntities()
            : base("name=TOLL_LocalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PaymentHistory> PaymentHistories { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<Toll> Tolls { get; set; }
        public virtual DbSet<TollPlaza> TollPlazas { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserVehicle> UserVehicles { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
    }
}
